### ISSUE TITLE
Add Navigation to the Site

### ISSUE THREAD

**Issue by ardalis** [ardalis/RegExLib.com#30]
The home page's layout should include:
- Logo top left that links to /
- Nav menu across top (responsive in narrower screens/devices)
- Login link if not logged in
- Username link if logged in
- Logout link if logged in

**Comment by ShadyNagy** [comment]
We will use Blazor?

**Comment by ardalis** [comment]
Possibly for logged in activities, not for public display. Site should be easily consumed by search engines, etc. without any need for javascript or signalR.

**Comment by ShadyNagy** [comment]
Blazor Client WebAssembly Prerendering will be solving for SEO Issues.
PA #47 
Daniel Roth -> https://github.com/danroth27/BlazorWebAssemblyWithPrerendering
