### ISSUE TITLE
[Discussion] Domain Model

### ISSUE THREAD

**Issue by antmdvs** [ardalis/RegExLib.com#46]
> Probably should create a new (open) issue to discuss this. My first thought is that Reactions are pretty much their own thing. You could have Reactions to anything. You just need some key for the "thing" and another key for the user and then either separate lists for Like or Dislike or just some kind of reaction type.
> 
> My next consideration is how will they be used? Do you show reactions on the user's home page? Maybe, but that's probably not their primary use. The primary use case is to show a count of reactions on a given resource. Think about reactions in Slack or Discord or even GitHub. You can add a reaction to this particular comment on this issue. The primary use case is "GetReactionsForResource(resourceKey)" which if there are several kinds of reactions does a group and count.
> 
> If I delete the resource, what should happen to its reactions? Either they're orphaned or they disappear with it.
> If I delete the user/author, same question. And probably same answer.
> 
> In neither case must it happen immediately as part of the transaction though. We can allow for eventual consistency, assuming we're not enforcing foreign keys at the data layer.
> 
> Looking at GitHub as an example, they show a count of reactions but also will show who reacted when you mouse over, so they're fetching more than just the counts. It's also worth noting that their key is probably the username, not userid, which is nice because that's what they display on mouseover (instead of an int or guid key that would be useless or would require a call to translate to a username). This too argues for Reactions to be part of the Expression aggregate. So that's probably what I would do. Expression as aggregate root, Reaction as part of the aggregate. Navigation property from Expression to List<Reaction>. Key-only properties on Reaction to ExpressionId and Username.

_Originally posted by @ardalis in https://github.com/ardalis/RegExLib.com/issues/34#issuecomment-654291086_

**Comment by antmdvs** [comment]
I think I follow. For those playing the home game:

![image](https://user-images.githubusercontent.com/17127310/87111037-6d89ee80-c236-11ea-9a72-fa6a23c30fb7.jpeg)

Now, since the [previous thinking](https://github.com/ardalis/RegExLib.com/pull/14#discussion_r447150017) has been revised, where would that leave Author? 

- Authors don’t change when their Expressions change
- Deleting an Author _probably_ deletes its Expressions but that may be eventually consistent I guess? (The UI could show “Anonymous” or similar if it’s AuthorId no longer exists — of course, this is also true even if deletes don’t cascade)

So maybe Author is either a singleton aggregate or we have a User-Author aggregate. Maybe both Author and User are just their own aggregates/aggregate roots.

How should I be thinking about this? I feel like I’m still missing something but I’m not sure what. Perhaps the domain insight hasn’t yet revealed itself 💡 :/

**Comment by antmdvs** [comment]
Would User be in a different bounded context (e.g.: User Account Management) since both User and Author are two different terms referring to the same concept?

**Comment by ShadyNagy** [comment]
I think Reader/Viewer will be not authenticated and if we create the user then he will be author only and wihout any role.
But if user created with role administrator then he had some more future like delete other things and control users.

**Comment by antmdvs** [comment]
> How should I be thinking about this? I feel like I’m still missing something but I’m not sure what.

/cc: @ardalis

**Comment by ardalis** [comment]
So, I like to think first in terms of use cases or scenarios:

## Regular Expressions
- As an author, I can add a new regular expression to my collection of regexes.
- As an author I can update my regular expressions
- As an author I can delete my regular expressions
- As a user, I can become an Author by creating my first regular expression

## Feedback
- As a user, I can add a rating or reaction to a regular expression
- As a user, I can remove [same]
- As a user, I can update [same]

## Design Questions

- Does a reaction have a navigation property to an expression? Or just an ID.
- Do reactions even need to live in the same data model or bounded context as the thing to which they're reacting?
  - Maybe feedback is a separate BC or microservice?
- What should happen to a reaction when its target is deleted or missing?
  - When would this matter? It's orphan data, but it'll never be shown anywhere. Clean it up with a batch process periodically and leave it alone.
- Do User and Author need to be tightly coupled at compile time?
  - Can we just use an identifier like a UserId GUID or email address, etc.

If we follow the approach here:

- Author is aggregate root
- Expression is child of Author
- User is not navigation property of anything
  - UserId or surrogate key is used by Author, Rating

- No coupling between Authors, Users, Ratings
- We can delete Authors or Expressions without impact to Ratings
- We can delete Ratings easily

**Comment by antmdvs** [comment]
Answered in livestream: https://youtu.be/aab5ocDSmNg?t=3089
