### ISSUE TITLE
Add Regular Expression entity

### ISSUE THREAD

**Issue by ardalis** [ardalis/RegExLib.com#7]
We would like to import some or all of the existing expressions, so it would be good if the new model made this easy to do.

A regular expression consists of:
- Id
- Title
- Expression
- Description

All of these are required.

Expressions have an author.

The current data model shows a list of up to 3 strings the expression matches and 3 that it doesn't. I anticipate changing how this works in the new model. My plan is to be able to list an arbitrary number of matching/non-matching strings and for each one specify which regex engine was used. It's possible that an expression works one way using the .NET regex but a different way using JavaScript, Java, or Perl. So, for now we'll leave the matching/nonmatching strings off.

**Comment by antmdvs** [comment]
Should the entity have a `Validate` method and/or `Timeout` property per #13?

**Comment by ardalis** [comment]
Seems like the engine, not the expression, should have these countermeasures, based on what the other issue said, right?

**Comment by antmdvs** [comment]
I guess I was thinking the `RegularExpression` should be able to validate itself and ideally not even be able to be constructed with a malicious `Expression`. But yes, assuming #13 was written correctly :) we would at least need a `RegularExpressionEngine` entity, correct? Or a RegularExpressionValidator.. or both.

**Comment by ardalis** [comment]
Yeah the trick is that expressions are “valid” only in the context of the engine evaluating them. So I think that needs to be in there somewhere. I need to learn more about “evil” expressions and how to detect them, though.

**Comment by antmdvs** [comment]
Same here. I'm guessing that as with any user input validation, blacklisting regex (sub-)expressions is a losing battle and we may have to fallback to runtime measures (e.g. timeouts), assuming availability for all RE engines.
