### ISSUE TITLE
Add Author entity

### ISSUE THREAD

**Issue by ardalis** [ardalis/RegExLib.com#8]
An author should be associated with an identity user.

An author should have a list of expressions they own.

Authors should also have
- Full name
- Username

User name should not be an email address. Disallow '@' in the user name.

**Comment by ShadyNagy** [comment]
`An author should be associated with an identity user.`
Did you mean database level must be a relation? or you mean Author has one ApplicationUser?
I tried to make a relation between the Author entity and ApllicationUser but it will cause cycle dependency.
Any suggestions, please.

**Comment by ardalis** [comment]
I would give Author an Id (as an Entity it will have one) as well as a UserId property that matches the ApplicationUser id. But without any database relationship - just a string property.
